functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
 - Корзина хранится в сессии браузера
 - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
 - Магазин будет SPA-приложение, которое не перезагружает страницу

non-functional:
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт нужно протестировать на совместимость с последними версиями браузеров

implicit:
 - Пользователь не может редактировать описание товара
